export const TEMPLATES_DATA = [
  { id: 1, name: 'Welcome Email', type: 'Email', content: 'Welcome to our platform! We are excited to have you on board.', created: '2025-10-26' },
  { id: 2, name: 'Order Confirmation', type: 'SMS', content: 'Your order has been confirmed. Order ID: {{orderId}}', created: '2025-10-25' },
  { id: 3, name: 'Password Reset', type: 'Email', content: 'Click here to reset your password: {{resetLink}}', created: '2025-10-24' },
  { id: 4, name: 'Flash Sale Alert', type: 'In app SMS', content: 'Flash sale is live! Get 50% off on all products.', created: '2025-10-23' },
  { id: 5, name: 'Shipping Update', type: 'Email', content: 'Your order has been shipped. Track: {{trackingId}}', created: '2025-10-22' },
  { id: 6, name: 'Payment Received', type: 'SMS', content: 'Thank you! Your payment has been received successfully.', created: '2025-10-21' },
  { id: 7, name: 'Account Verification', type: 'Email', content: 'Please verify your account by clicking: {{verifyLink}}', created: '2025-10-20' },
  { id: 8, name: 'Discount Offer', type: 'In app SMS', content: 'Special discount just for you! Use code: {{discountCode}}', created: '2025-10-19' },
  { id: 9, name: 'Order Delivered', type: 'SMS', content: 'Your order has been delivered. Thank you for shopping!', created: '2025-10-18' },
  { id: 10, name: 'Newsletter', type: 'Email', content: 'Check out our latest products and offers this month.', created: '2025-10-17' },
  { id: 11, name: 'Cart Abandonment', type: 'Email', content: 'You left items in your cart! Complete your purchase now.', created: '2025-10-16' },
  { id: 12, name: 'Order Cancelled', type: 'SMS', content: 'Your order has been cancelled. Refund will be processed.', created: '2025-10-15' },
  { id: 13, name: 'Product Review Request', type: 'Email', content: 'How was your experience? Please leave a review for {{productName}}', created: '2025-10-14' },
  { id: 14, name: 'Wishlist Reminder', type: 'In app SMS', content: 'Items in your wishlist are now on sale!', created: '2025-10-13' },
  { id: 15, name: 'Account Locked', type: 'Email', content: 'Your account has been locked due to suspicious activity.', created: '2025-10-12' },
  { id: 16, name: 'Referral Bonus', type: 'SMS', content: 'You earned a referral bonus! Check your account.', created: '2025-10-11' },
  { id: 17, name: 'Low Stock Alert', type: 'In app SMS', content: 'Hurry! Only {{quantity}} items left in stock.', created: '2025-10-10' },
  { id: 18, name: 'Birthday Wishes', type: 'Email', content: 'Happy Birthday! Here is a special gift for you: {{giftCode}}', created: '2025-10-09' },
  { id: 19, name: 'Return Approved', type: 'SMS', content: 'Your return request has been approved. Return ID: {{returnId}}', created: '2025-10-08' },
  { id: 20, name: 'Subscription Renewal', type: 'Email', content: 'Your subscription will renew on {{renewalDate}}', created: '2025-10-07' },
  { id: 21, name: 'Price Drop Alert', type: 'In app SMS', content: 'Price dropped on {{productName}}! Buy now and save.', created: '2025-10-06' },
  { id: 22, name: 'Security Alert', type: 'Email', content: 'New login detected from {{location}}. Was this you?', created: '2025-10-05' },
  { id: 23, name: 'Loyalty Points', type: 'SMS', content: 'You have {{points}} loyalty points. Redeem them now!', created: '2025-10-04' },
  { id: 24, name: 'Pre-Order Available', type: 'Email', content: 'Pre-order {{productName}} now and get early access!', created: '2025-10-03' },
  { id: 25, name: 'Survey Request', type: 'In app SMS', content: 'Help us improve! Take a quick 2-minute survey.', created: '2025-10-02' },
  { id: 26, name: 'Warranty Expiring', type: 'Email', content: 'Your warranty for {{productName}} expires soon. Extend now!', created: '2025-10-01' },
  { id: 27, name: 'Back in Stock', type: 'SMS', content: '{{productName}} is back in stock! Order now.', created: '2025-09-30' },
  { id: 28, name: 'Exclusive Deal', type: 'Email', content: 'Exclusive deal just for you! Get {{discount}}% off.', created: '2025-09-29' },
  { id: 29, name: 'Order Delayed', type: 'SMS', content: 'Your order is delayed. New delivery date: {{newDate}}', created: '2025-09-28' },
  { id: 30, name: 'Account Upgrade', type: 'In app SMS', content: 'Upgrade to premium and unlock exclusive benefits!', created: '2025-09-27' },
  { id: 31, name: 'Payment Failed', type: 'Email', content: 'Payment failed for order {{orderId}}. Please retry.', created: '2025-09-26' },
  { id: 32, name: 'Seasonal Sale', type: 'SMS', content: 'Seasonal sale is live! Up to 70% off on selected items.', created: '2025-09-25' },
  { id: 33, name: 'New Feature', type: 'In app SMS', content: 'Check out our new feature: {{featureName}}!', created: '2025-09-24' },
  { id: 34, name: 'Subscription Cancelled', type: 'Email', content: 'Your subscription has been cancelled. We will miss you!', created: '2025-09-23' },
  { id: 35, name: 'Giveaway Entry', type: 'SMS', content: 'You are entered in our giveaway! Winner announced on {{date}}', created: '2025-09-22' },
  { id: 36, name: 'App Update', type: 'In app SMS', content: 'New app version available. Update now for better experience!', created: '2025-09-21' },
  { id: 37, name: 'Invoice Generated', type: 'Email', content: 'Your invoice for order {{orderId}} is ready. Download now.', created: '2025-09-20' },
  { id: 38, name: 'Maintenance Notice', type: 'SMS', content: 'Scheduled maintenance on {{date}}. Service may be unavailable.', created: '2025-09-19' },
  { id: 39, name: 'Reward Unlocked', type: 'Email', content: 'Congratulations! You unlocked a new reward: {{rewardName}}', created: '2025-09-18' },
  { id: 40, name: 'Feedback Request', type: 'In app SMS', content: 'How was your shopping experience? Rate us now!', created: '2025-09-17' },
  { id: 41, name: 'VIP Invitation', type: 'Email', content: 'You are invited to our VIP program! Join now for exclusive perks.', created: '2025-09-16' },
  { id: 42, name: 'Flash Deal Ending', type: 'SMS', content: 'Flash deal ending in 1 hour! Grab it before it is gone.', created: '2025-09-15' },
];

export const NOTIFICATION_LOGS = [
  { id: 1, dateTime: '7/14/2025, 9:11:16 PM', sentBy: 'admin', audience: 'Specific Users', channel: 'In app SMS', status: 'Sent', title: 'Flash Sale Alert', message: 'Get 50% off on all electronics!' },
  { id: 2, dateTime: '7/14/2025, 1:54:46 PM', sentBy: 'admin', audience: 'Specific Users', channel: 'In app SMS', status: 'Sent', title: 'New Arrivals', message: 'Check out our new collection of smartphones' },
  { id: 3, dateTime: '7/7/2025, 5:54:22 PM', sentBy: 'admin', audience: 'Specific Users', channel: 'In app SMS', status: 'Sent', title: 'Weekend Special', message: 'Special discounts for the weekend' },
  { id: 4, dateTime: '7/6/2025, 3:08:39 AM', sentBy: 'admin', audience: 'Specific Users', channel: 'In app SMS', status: 'Sent', title: 'Order Confirmation', message: 'Your order has been confirmed successfully' },
  { id: 5, dateTime: '7/5/2025, 2:30:15 PM', sentBy: 'admin', audience: 'All Users', channel: 'Email', status: 'Failed', title: 'System Maintenance', message: 'Scheduled maintenance notification' },
  { id: 6, dateTime: '7/4/2025, 10:45:22 AM', sentBy: 'admin', audience: 'All Retailers', channel: 'Email', status: 'Sent', title: 'Retailer Update', message: 'New features available for retailers' },
  { id: 7, dateTime: '7/3/2025, 8:20:30 PM', sentBy: 'admin', audience: 'All Customers', channel: 'SMS', status: 'Sent', title: 'Payment Received', message: 'Thank you for your payment' },
  { id: 8, dateTime: '7/2/2025, 4:15:18 PM', sentBy: 'admin', audience: 'Specific Users', channel: 'In app SMS', status: 'Sent', title: 'Reward Points', message: 'You have earned 100 reward points' },
  { id: 9, dateTime: '7/1/2025, 11:30:45 AM', sentBy: 'admin', audience: 'All Users', channel: 'Email', status: 'Sent', title: 'Welcome Aboard', message: 'Welcome to our platform!' },
  { id: 10, dateTime: '6/30/2025, 6:20:10 PM', sentBy: 'admin', audience: 'All Customers', channel: 'SMS', status: 'Failed', title: 'Delivery Update', message: 'Your order is out for delivery' },
  { id: 11, dateTime: '6/29/2025, 3:45:30 PM', sentBy: 'admin', audience: 'Specific Users', channel: 'In app SMS', status: 'Sent', title: 'Cart Reminder', message: 'You have items waiting in your cart' },
  { id: 12, dateTime: '6/28/2025, 9:15:20 AM', sentBy: 'admin', audience: 'All Retailers', channel: 'Email', status: 'Sent', title: 'Monthly Report', message: 'Your monthly sales report is ready' },
  { id: 13, dateTime: '6/27/2025, 7:50:40 PM', sentBy: 'admin', audience: 'All Users', channel: 'In app SMS', status: 'Sent', title: 'App Update', message: 'New version available with exciting features' },
  { id: 14, dateTime: '6/26/2025, 2:10:55 PM', sentBy: 'admin', audience: 'All Customers', channel: 'SMS', status: 'Sent', title: 'Feedback Request', message: 'Please rate your recent purchase' },
  { id: 15, dateTime: '6/25/2025, 5:35:15 PM', sentBy: 'admin', audience: 'Specific Users', channel: 'Email', status: 'Failed', title: 'Account Alert', message: 'Unusual activity detected on your account' },
  { id: 16, dateTime: '6/24/2025, 11:20:30 AM', sentBy: 'admin', audience: 'All Users', channel: 'Email', status: 'Sent', title: 'Newsletter', message: 'Check out our latest products and offers' },
  { id: 17, dateTime: '6/23/2025, 4:45:15 PM', sentBy: 'admin', audience: 'All Customers', channel: 'SMS', status: 'Sent', title: 'Order Shipped', message: 'Your order is on the way!' },
  { id: 18, dateTime: '6/22/2025, 8:30:50 PM', sentBy: 'admin', audience: 'Specific Users', channel: 'In app SMS', status: 'Failed', title: 'Price Drop', message: 'Items in your wishlist are now cheaper' },
  { id: 19, dateTime: '6/21/2025, 1:15:25 PM', sentBy: 'admin', audience: 'All Retailers', channel: 'Email', status: 'Sent', title: 'Inventory Alert', message: 'Low stock alert for multiple products' },
  { id: 20, dateTime: '6/20/2025, 6:50:40 AM', sentBy: 'admin', audience: 'All Users', channel: 'In app SMS', status: 'Sent', title: 'Birthday Offer', message: 'Special birthday discount for you!' },
  { id: 21, dateTime: '6/19/2025, 10:25:15 PM', sentBy: 'admin', audience: 'Specific Users', channel: 'SMS', status: 'Sent', title: 'Return Approved', message: 'Your return request has been approved' },
  { id: 22, dateTime: '6/18/2025, 3:40:30 PM', sentBy: 'admin', audience: 'All Customers', channel: 'Email', status: 'Sent', title: 'Loyalty Rewards', message: 'You have earned new loyalty points' },
  { id: 23, dateTime: '6/17/2025, 7:55:45 AM', sentBy: 'admin', audience: 'All Users', channel: 'In app SMS', status: 'Failed', title: 'Flash Deal', message: 'Limited time flash deal on electronics' },
  { id: 24, dateTime: '6/16/2025, 12:10:20 PM', sentBy: 'admin', audience: 'Specific Users', channel: 'Email', status: 'Sent', title: 'Subscription Renewal', message: 'Your subscription will renew soon' },
  { id: 25, dateTime: '6/15/2025, 5:35:55 PM', sentBy: 'admin', audience: 'All Retailers', channel: 'SMS', status: 'Sent', title: 'Payment Processed', message: 'Your payment has been processed successfully' },
  { id: 26, dateTime: '6/14/2025, 9:20:10 AM', sentBy: 'admin', audience: 'All Users', channel: 'Email', status: 'Sent', title: 'Security Update', message: 'Important security update for your account' },
  { id: 27, dateTime: '6/13/2025, 2:45:35 PM', sentBy: 'admin', audience: 'All Customers', channel: 'In app SMS', status: 'Sent', title: 'Back in Stock', message: 'Your favorite product is back in stock' },
  { id: 28, dateTime: '6/12/2025, 8:15:50 PM', sentBy: 'admin', audience: 'Specific Users', channel: 'SMS', status: 'Failed', title: 'Order Delayed', message: 'Your order delivery is delayed' },
  { id: 29, dateTime: '6/11/2025, 11:40:25 AM', sentBy: 'admin', audience: 'All Users', channel: 'Email', status: 'Sent', title: 'Survey Request', message: 'Help us improve by taking a quick survey' },
  { id: 30, dateTime: '6/10/2025, 4:05:40 PM', sentBy: 'admin', audience: 'All Retailers', channel: 'In app SMS', status: 'Sent', title: 'New Feature', message: 'Check out our new dashboard features' },
  { id: 31, dateTime: '6/9/2025, 7:30:15 AM', sentBy: 'admin', audience: 'Specific Users', channel: 'Email', status: 'Sent', title: 'Exclusive Offer', message: 'Exclusive offer just for you!' },
  { id: 32, dateTime: '6/8/2025, 1:55:30 PM', sentBy: 'admin', audience: 'All Customers', channel: 'SMS', status: 'Sent', title: 'Order Delivered', message: 'Your order has been delivered successfully' },
  { id: 33, dateTime: '6/7/2025, 6:20:45 PM', sentBy: 'admin', audience: 'All Users', channel: 'In app SMS', status: 'Sent', title: 'Maintenance Notice', message: 'Scheduled maintenance tonight' },
  { id: 34, dateTime: '6/6/2025, 10:45:20 AM', sentBy: 'admin', audience: 'Specific Users', channel: 'Email', status: 'Failed', title: 'Password Changed', message: 'Your password was recently changed' },
  { id: 35, dateTime: '6/5/2025, 3:10:35 PM', sentBy: 'admin', audience: 'All Retailers', channel: 'SMS', status: 'Sent', title: 'Commission Update', message: 'Your commission has been updated' },
  { id: 36, dateTime: '6/4/2025, 8:35:50 PM', sentBy: 'admin', audience: 'All Users', channel: 'Email', status: 'Sent', title: 'Seasonal Sale', message: 'Huge seasonal sale starting tomorrow' },
  { id: 37, dateTime: '6/3/2025, 12:00:15 PM', sentBy: 'admin', audience: 'All Customers', channel: 'In app SMS', status: 'Sent', title: 'Referral Bonus', message: 'You earned a referral bonus!' },
  { id: 38, dateTime: '6/2/2025, 5:25:30 AM', sentBy: 'admin', audience: 'Specific Users', channel: 'SMS', status: 'Sent', title: 'Review Request', message: 'Please review your recent purchase' },
  { id: 39, dateTime: '6/1/2025, 9:50:45 AM', sentBy: 'admin', audience: 'All Users', channel: 'Email', status: 'Sent', title: 'App Update', message: 'New app version available now' },
  { id: 40, dateTime: '5/31/2025, 2:15:20 PM', sentBy: 'admin', audience: 'All Retailers', channel: 'In app SMS', status: 'Failed', title: 'Stock Alert', message: 'Multiple products are low on stock' },
  { id: 41, dateTime: '5/30/2025, 7:40:35 PM', sentBy: 'admin', audience: 'Specific Users', channel: 'Email', status: 'Sent', title: 'VIP Invitation', message: 'You are invited to our VIP program' },
  { id: 42, dateTime: '5/29/2025, 11:05:50 AM', sentBy: 'admin', audience: 'All Customers', channel: 'SMS', status: 'Sent', title: 'Warranty Expiring', message: 'Your product warranty expires soon' },
];
