export const REVIEWS_DATA = [
  {
    id: 1,
    productName: 'Rivano 44W Flash Charger',
    productImage: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=200&h=200&fit=crop',
    reviewerName: 'Rohit Kumar',
    reviewerEmail: 'rohit@gmail.com',
    rating: 5,
    comment: 'Excellent product! Fast charging works perfectly. Highly recommended for daily use.',
    date: '2025-07-09',
    status: 'Pending',
    verified: true,
    helpful: 15,
    category: 'Chargers'
  },
  {
    id: 2,
    productName: 'Boat Airdopes 141',
    productImage: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=200&h=200&fit=crop',
    reviewerName: 'Priya Sharma',
    reviewerEmail: 'priya@gmail.com',
    rating: 4,
    comment: 'Good sound quality and comfortable fit. Battery life could be better.',
    date: '2025-08-15',
    status: 'Approved',
    verified: true,
    helpful: 23,
    category: 'Earphones'
  },
  {
    id: 3,
    productName: 'OnePlus 85W Dash Charger',
    productImage: 'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=200&h=200&fit=crop',
    reviewerName: 'Amit Singh',
    reviewerEmail: 'amit@gmail.com',
    rating: 5,
    comment: 'Super fast charging! My phone charges in 30 minutes. Worth every penny.',
    date: '2025-09-20',
    status: 'Approved',
    verified: true,
    helpful: 45,
    category: 'Chargers'
  },
  {
    id: 4,
    productName: 'Mi Power Bank 20000mAh',
    productImage: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=200&h=200&fit=crop',
    reviewerName: 'Sneha Patel',
    reviewerEmail: 'sneha@gmail.com',
    rating: 3,
    comment: 'Average product. Takes too long to charge itself.',
    date: '2025-10-01',
    status: 'Flagged',
    verified: false,
    helpful: 5,
    category: 'Power Banks'
  },
  {
    id: 5,
    productName: 'Boat Blastpods',
    productImage: 'https://images.unsplash.com/photo-1606400082777-ef05f3c5cde9?w=200&h=200&fit=crop',
    reviewerName: 'Rahul Verma',
    reviewerEmail: 'rahul@gmail.com',
    rating: 2,
    comment: 'Poor quality. Stopped working after 2 weeks. Not worth the money.',
    date: '2025-10-10',
    status: 'Rejected',
    verified: true,
    helpful: 8,
    category: 'Earphones'
  },
  {
    id: 6,
    productName: 'Samsung 25W Fast Charger',
    productImage: 'https://images.unsplash.com/photo-1591290619762-c588a07e5770?w=200&h=200&fit=crop',
    reviewerName: 'Neha Gupta',
    reviewerEmail: 'neha@gmail.com',
    rating: 5,
    comment: 'Perfect charger for my Samsung phone. Original quality and fast delivery.',
    date: '2025-10-12',
    status: 'Approved',
    verified: true,
    helpful: 18,
    category: 'Chargers'
  },
  {
    id: 7,
    productName: 'JBL Wireless Speaker',
    productImage: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=200&h=200&fit=crop',
    reviewerName: 'Vikram Rao',
    reviewerEmail: 'vikram@gmail.com',
    rating: 4,
    comment: 'Great bass and sound quality. Battery lasts for 8 hours.',
    date: '2025-10-15',
    status: 'Pending',
    verified: true,
    helpful: 12,
    category: 'Speakers'
  },
  {
    id: 8,
    productName: 'Airpods Pro Clone',
    productImage: 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=200&h=200&fit=crop',
    reviewerName: 'Harsh Kumar',
    reviewerEmail: 'harsh@gmail.com',
    rating: 1,
    comment: 'Fake product! This is a scam. Do not buy.',
    date: '2025-10-18',
    status: 'Flagged',
    verified: false,
    helpful: 2,
    category: 'Earphones'
  },
  {
    id: 9,
    productName: 'Xiaomi 33W Charger',
    productImage: 'https://images.unsplash.com/photo-1624823183493-ed5832f48f18?w=200&h=200&fit=crop',
    reviewerName: 'Anjali Desai',
    reviewerEmail: 'anjali@gmail.com',
    rating: 5,
    comment: 'Charges my phone super fast. Compact design and affordable price.',
    date: '2025-10-20',
    status: 'Approved',
    verified: true,
    helpful: 30,
    category: 'Chargers'
  },
  {
    id: 10,
    productName: 'Boat Killer Earphones',
    productImage: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=200&h=200&fit=crop',
    reviewerName: 'Manish Jain',
    reviewerEmail: 'manish@gmail.com',
    rating: 4,
    comment: 'Good product for the price. Comfortable and decent sound.',
    date: '2025-10-22',
    status: 'Pending',
    verified: true,
    helpful: 7,
    category: 'Earphones'
  },
  {
    id: 11,
    productName: 'Sony Wireless Headphones',
    productImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=200&h=200&fit=crop',
    reviewerName: 'Kavita Rao',
    reviewerEmail: 'kavita@gmail.com',
    rating: 5,
    comment: 'Noise cancellation is superb! Best headphones I ever bought.',
    date: '2025-10-11',
    status: 'Approved',
    verified: true,
    helpful: 52,
    category: 'Headphones'
  },
  {
    id: 12,
    productName: 'Anker USB-C Cable',
    productImage: 'https://images.unsplash.com/photo-1589492477829-5e65395b66cc?w=200&h=200&fit=crop',
    reviewerName: 'Deepak Kumar',
    reviewerEmail: 'deepak@gmail.com',
    rating: 4,
    comment: 'Durable and long lasting. Good value for money.',
    date: '2025-09-28',
    status: 'Approved',
    verified: true,
    helpful: 19,
    category: 'Cables'
  },
  {
    id: 13,
    productName: 'Realme Buds Air',
    productImage: 'https://images.unsplash.com/photo-1598331668280-84ba1c4b5584?w=200&h=200&fit=crop',
    reviewerName: 'Pooja Mehta',
    reviewerEmail: 'pooja@gmail.com',
    rating: 3,
    comment: 'Decent for the price but connection drops sometimes.',
    date: '2025-10-05',
    status: 'Pending',
    verified: false,
    helpful: 4,
    category: 'Earphones'
  },
  {
    id: 14,
    productName: 'Portronics Wireless Mouse',
    productImage: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=200&h=200&fit=crop',
    reviewerName: 'Ravi Shankar',
    reviewerEmail: 'ravi@gmail.com',
    rating: 4,
    comment: 'Smooth scrolling and comfortable grip. Good battery life.',
    date: '2025-10-08',
    status: 'Approved',
    verified: true,
    helpful: 14,
    category: 'Accessories'
  },
  {
    id: 15,
    productName: 'Zebronics Gaming Keyboard',
    productImage: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=200&h=200&fit=crop',
    reviewerName: 'Arjun Patel',
    reviewerEmail: 'arjun@gmail.com',
    rating: 2,
    comment: 'Keys feel cheap and RGB lighting is uneven.',
    date: '2025-10-14',
    status: 'Flagged',
    verified: true,
    helpful: 6,
    category: 'Accessories'
  },
];
